//cart
export const ADD_TO_CART = 'ADD_TO_CART'
export const DELETE_TO_ITEM_CART = 'DELETE_TO_ITEM_CART'
export const UPDATE_TO_ITEM_CART = 'UPDATE_TO_ITEM_CART'

//Get_Products
export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_COLORS = 'GET_COLORS'
export const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS'
export const ADD_PRODUCTS = 'ADD_PRODUCTS'
export const GET_DETAIL_PRODUCT = 'GET_DETAIL_PRODUCT'
export const REQUEST_DETAIL_PRODUCT = 'REQUEST_DETAIL_PRODUCT'
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'

// category
export const REQUEST_CATEGORY = 'REQUEST_CATEGORY'
export const GET_CATEGORY = 'GET_CATEGORY'
export const ADD_CATEGORY = 'ADD_CATEGORY'
export const REQUEST_DETAIL_CATEGORY = 'REQUEST_DETAIL_CATEGORY'
export const GET_DETAIL_CATEGORY = 'GET_DETAIL_CATEGORY'
export const DELETE_CATEGORY = 'DELETE_CATEGORY'
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY'

// sign in popup
export const CHANGE_OPEN = 'CHANGE_OPEN'
// Authe
export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const REQUEST_REGISTER = 'REQUEST_REGISTER'
export const REQUEST_LOGIN_SOCIAL = 'REQUEST_LOGIN_SOCIAL'
// alert
export const ALTER_CHANGE = 'ALERT_CHANGE'
//user
export const REQUEST_PROFILE = 'REQUEST_PROFILE'
export const GET_PROFILE = 'GET_PROFILE'
export const UPDATE_PROFILE = 'UPDATE_PROFILE'
//loading
export const LOADING_CHANGE = 'LOADING_CHANGE'
